FROM uptimetomcat9:latest
ADD exercise.py /root/exercise.py
ADD exercise.exe /root/exercise.exe
RUN chmod 755 /root/exercise.py
RUN chmod 755 /root/exercise.exe
ADD entrypoint.sh /root/entrypoint.sh
RUN chmod 755 /root/entrypoint.sh
EXPOSE 8080
ENTRYPOINT ["/root/entrypoint.sh"]
